In [59]:
import pandas as pd

In [60]:
poke_csv="Resources/clean_data.csv"
poke_df= pd.read_csv(poke_csv)
poke_df

,#,Name,Type1,Type2,Total,HP,Attack,Defense,SpAtk,SpDef,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [61]:
short_df=poke_df.drop(["Total", "HP", "Attack", "Defense", "SpAtk", "SpDef", "Speed", "Legendary"], axis=1)
short_df

       #                   Name    Type1   Type2  Generation
0      1              Bulbasaur    Grass  Poison           1
1      2                Ivysaur    Grass  Poison           1
2      3               Venusaur    Grass  Poison           1
3      3  VenusaurMega Venusaur    Grass  Poison           1
4      4             Charmander     Fire     NaN           1
..   ...                    ...      ...     ...         ...
795  719                Diancie     Rock   Fairy           6
796  719    DiancieMega Diancie     Rock   Fairy           6
797  720    HoopaHoopa Confined  Psychic   Ghost           6
798  720     HoopaHoopa Unbound  Psychic    Dark           6
799  721              Volcanion     Fire   Water           6

[800 rows x 5 columns]

In [66]:
#Clean the dataframe to include only relevant columns and create a recode column for each type 
short_df["Type1_Recode"] = ""
short_df["Type2_Recode"] = ""
short_df

,#,Name,Type1,Type2,Generation,Type1_Recode,Type2_Recode
0,1,Bulbasaur,Grass,Poison,1,,
1,2,Ivysaur,Grass,Poison,1,,
2,3,Venusaur,Grass,Poison,1,,
3,3,VenusaurMega Venusaur,Grass,Poison,1,,
4,4,Charmander,Fire,NaN,1,,
...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,6,,
796,719,DiancieMega Diancie,Rock,Fairy,6,,
797,720,HoopaHoopa Confined,Psychic,Ghost,6,,
798,720,HoopaHoopa Unbound,Psychic,Dark,6,,
799,721,Volcanion,Fire,Water,6,,

In [63]:
#Gather list of unique pokemon types
type1_list = short_df["Type1"].unique()
type1_list

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [70]:
#Confirm number of unique types
len(type1_list)

18

In [71]:
#iterate through DF to recode the listed type1 for each pokemon 
for row,col in short_df.iterrows(): 
    if short_df["Type1"][row] == "Grass": 
        short_df["Type1_Recode"][row] = 1
    elif short_df["Type1"][row] == "Fire": 
        short_df["Type1_Recode"][row] = 2
    elif short_df["Type1"][row] == "Water": 
        short_df["Type1_Recode"][row] = 3
    elif short_df["Type1"][row] == "Bug": 
        short_df["Type1_Recode"][row] = 4
    elif short_df["Type1"][row] == "Normal": 
        short_df["Type1_Recode"][row] = 5
    elif short_df["Type1"][row] == "Poison": 
        short_df["Type1_Recode"][row] = 6
    elif short_df["Type1"][row] == "Electric": 
        short_df["Type1_Recode"][row] = 7
    elif short_df["Type1"][row] == "Ground": 
        short_df["Type1_Recode"][row] = 8
    elif short_df["Type1"][row] == "Fairy": 
        short_df["Type1_Recode"][row] = 9
    elif short_df["Type1"][row] == "Fighting": 
        short_df["Type1_Recode"][row] = 10
    elif short_df["Type1"][row] == "Psychic": 
        short_df["Type1_Recode"][row] = 11
    elif short_df["Type1"][row] == "Rock": 
        short_df["Type1_Recode"][row] = 12
    elif short_df["Type1"][row] == "Ghost": 
        short_df["Type1_Recode"][row] = 13
    elif short_df["Type1"][row] == "Ice": 
        short_df["Type1_Recode"][row] = 14
    elif short_df["Type1"][row] == "Dragon": 
        short_df["Type1_Recode"][row] = 15
    elif short_df["Type1"][row] == "Dark": 
        short_df["Type1_Recode"][row] = 16
    elif short_df["Type1"][row] == "Steel": 
        short_df["Type1_Recode"][row] = 17
    elif short_df["Type1"][row] == "Flying": 
        short_df["Type1_Recode"][row] = 18
        
short_df

/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,#,Name,Type1,Type2,Generation,Type1_Recode,Type2_Recode
0,1,Bulbasaur,Grass,Poison,1,1,6
1,2,Ivysaur,Grass,Poison,1,1,6
2,3,Venusaur,Grass,Poison,1,1,6
3,3,VenusaurMega Venusaur,Grass,Poison,1,1,6
4,4,Charmander,Fire,NaN,1,2,
...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,6,12,9
796,719,DiancieMega Diancie,Rock,Fairy,6,12,9
797,720,HoopaHoopa Confined,Psychic,Ghost,6,11,13
798,720,HoopaHoopa Unbound,Psychic,Dark,6,11,16
799,721,Volcanion,Fire,Water,6,2,3

In [72]:
#iterate through DF to recode the listed type2 for each pokemon 
for row,col in short_df.iterrows(): 
    if short_df["Type2"][row] == "Grass": 
        short_df["Type2_Recode"][row] = 1
    elif short_df["Type2"][row] == "Fire": 
        short_df["Type2_Recode"][row] = 2
    elif short_df["Type2"][row] == "Water": 
        short_df["Type2_Recode"][row] = 3
    elif short_df["Type2"][row] == "Bug": 
        short_df["Type2_Recode"][row] = 4
    elif short_df["Type2"][row] == "Normal": 
        short_df["Type2_Recode"][row] = 5
    elif short_df["Type2"][row] == "Poison": 
        short_df["Type2_Recode"][row] = 6
    elif short_df["Type2"][row] == "Electric": 
        short_df["Type2_Recode"][row] = 7
    elif short_df["Type2"][row] == "Ground": 
        short_df["Type2_Recode"][row] = 8
    elif short_df["Type2"][row] == "Fairy": 
        short_df["Type2_Recode"][row] = 9
    elif short_df["Type2"][row] == "Fighting": 
        short_df["Type2_Recode"][row] = 10
    elif short_df["Type2"][row] == "Psychic": 
        short_df["Type2_Recode"][row] = 11
    elif short_df["Type2"][row] == "Rock": 
        short_df["Type2_Recode"][row] = 12
    elif short_df["Type2"][row] == "Ghost": 
        short_df["Type2_Recode"][row] = 13
    elif short_df["Type2"][row] == "Ice": 
        short_df["Type2_Recode"][row] = 14
    elif short_df["Type2"][row] == "Dragon": 
        short_df["Type2_Recode"][row] = 15
    elif short_df["Type2"][row] == "Dark": 
        short_df["Type2_Recode"][row] = 16
    elif short_df["Type2"][row] == "Steel": 
        short_df["Type2_Recode"][row] = 17
    elif short_df["Type2"][row] == "Flying": 
        short_df["Type2_Recode"][row] = 18
        
short_df

/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/Applications/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

,#,Name,Type1,Type2,Generation,Type1_Recode,Type2_Recode
0,1,Bulbasaur,Grass,Poison,1,1,6
1,2,Ivysaur,Grass,Poison,1,1,6
2,3,Venusaur,Grass,Poison,1,1,6
3,3,VenusaurMega Venusaur,Grass,Poison,1,1,6
4,4,Charmander,Fire,NaN,1,2,
...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,6,12,9
796,719,DiancieMega Diancie,Rock,Fairy,6,12,9
797,720,HoopaHoopa Confined,Psychic,Ghost,6,11,13
798,720,HoopaHoopa Unbound,Psychic,Dark,6,11,16
799,721,Volcanion,Fire,Water,6,2,3

In [76]:
short_df.to_csv(r'./Resources/poke_recode.csv', index = False, header=True)