In [4]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import pandas as pd

In [5]:
poke_csv="Resources/clean_data.csv"
poke_df= pd.read_csv(poke_csv)
poke_df

,#,Name,Type1,Type2,Total,HP,Attack,Defense,SpAtk,SpDef,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [6]:
short_df=poke_df.drop(["Total", "HP", "Attack", "Defense", "SpAtk", "SpDef", "Speed", "Legendary"], axis=1)
short_df

       #                   Name    Type1   Type2  Generation
0      1              Bulbasaur    Grass  Poison           1
1      2                Ivysaur    Grass  Poison           1
2      3               Venusaur    Grass  Poison           1
3      3  VenusaurMega Venusaur    Grass  Poison           1
4      4             Charmander     Fire     NaN           1
..   ...                    ...      ...     ...         ...
795  719                Diancie     Rock   Fairy           6
796  719    DiancieMega Diancie     Rock   Fairy           6
797  720    HoopaHoopa Confined  Psychic   Ghost           6
798  720     HoopaHoopa Unbound  Psychic    Dark           6
799  721              Volcanion     Fire   Water           6

[800 rows x 5 columns]

In [7]:
#Clean the dataframe to include only relevant columns and create a recode column for each type 
short_df["Type1_Recode"] = ""
short_df["Type2_Recode"] = ""
short_df

,#,Name,Type1,Type2,Generation,Type1_Recode,Type2_Recode
0,1,Bulbasaur,Grass,Poison,1,,
1,2,Ivysaur,Grass,Poison,1,,
2,3,Venusaur,Grass,Poison,1,,
3,3,VenusaurMega Venusaur,Grass,Poison,1,,
4,4,Charmander,Fire,NaN,1,,
...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,6,,
796,719,DiancieMega Diancie,Rock,Fairy,6,,
797,720,HoopaHoopa Confined,Psychic,Ghost,6,,
798,720,HoopaHoopa Unbound,Psychic,Dark,6,,
799,721,Volcanion,Fire,Water,6,,

In [8]:
#Gather list of unique pokemon types
type1_list = short_df["Type1"].unique()
type1_list

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [9]:
#Confirm number of unique types
len(type1_list)

18

In [10]:
#iterate through DF to recode the listed type1 for each pokemon 
for row,col in short_df.iterrows(): 
    if short_df["Type1"][row] == "Grass": 
        short_df["Type1_Recode"][row] = 1
    elif short_df["Type1"][row] == "Fire": 
        short_df["Type1_Recode"][row] = 2
    elif short_df["Type1"][row] == "Water": 
        short_df["Type1_Recode"][row] = 3
    elif short_df["Type1"][row] == "Bug": 
        short_df["Type1_Recode"][row] = 4
    elif short_df["Type1"][row] == "Normal": 
        short_df["Type1_Recode"][row] = 5
    elif short_df["Type1"][row] == "Poison": 
        short_df["Type1_Recode"][row] = 6
    elif short_df["Type1"][row] == "Electric": 
        short_df["Type1_Recode"][row] = 7
    elif short_df["Type1"][row] == "Ground": 
        short_df["Type1_Recode"][row] = 8
    elif short_df["Type1"][row] == "Fairy": 
        short_df["Type1_Recode"][row] = 9
    elif short_df["Type1"][row] == "Fighting": 
        short_df["Type1_Recode"][row] = 10
    elif short_df["Type1"][row] == "Psychic": 
        short_df["Type1_Recode"][row] = 11
    elif short_df["Type1"][row] == "Rock": 
        short_df["Type1_Recode"][row] = 12
    elif short_df["Type1"][row] == "Ghost": 
        short_df["Type1_Recode"][row] = 13
    elif short_df["Type1"][row] == "Ice": 
        short_df["Type1_Recode"][row] = 14
    elif short_df["Type1"][row] == "Dragon": 
        short_df["Type1_Recode"][row] = 15
    elif short_df["Type1"][row] == "Dark": 
        short_df["Type1_Recode"][row] = 16
    elif short_df["Type1"][row] == "Steel": 
        short_df["Type1_Recode"][row] = 17
    elif short_df["Type1"][row] == "Flying": 
        short_df["Type1_Recode"][row] = 18
        
short_df

C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,#,Name,Type1,Type2,Generation,Type1_Recode,Type2_Recode
0,1,Bulbasaur,Grass,Poison,1,1,
1,2,Ivysaur,Grass,Poison,1,1,
2,3,Venusaur,Grass,Poison,1,1,
3,3,VenusaurMega Venusaur,Grass,Poison,1,1,
4,4,Charmander,Fire,NaN,1,2,
...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,6,12,
796,719,DiancieMega Diancie,Rock,Fairy,6,12,
797,720,HoopaHoopa Confined,Psychic,Ghost,6,11,
798,720,HoopaHoopa Unbound,Psychic,Dark,6,11,
799,721,Volcanion,Fire,Water,6,2,

In [11]:
#iterate through DF to recode the listed type2 for each pokemon 
for row,col in short_df.iterrows(): 
    if short_df["Type2"][row] == "Grass": 
        short_df["Type2_Recode"][row] = 1
    elif short_df["Type2"][row] == "Fire": 
        short_df["Type2_Recode"][row] = 2
    elif short_df["Type2"][row] == "Water": 
        short_df["Type2_Recode"][row] = 3
    elif short_df["Type2"][row] == "Bug": 
        short_df["Type2_Recode"][row] = 4
    elif short_df["Type2"][row] == "Normal": 
        short_df["Type2_Recode"][row] = 5
    elif short_df["Type2"][row] == "Poison": 
        short_df["Type2_Recode"][row] = 6
    elif short_df["Type2"][row] == "Electric": 
        short_df["Type2_Recode"][row] = 7
    elif short_df["Type2"][row] == "Ground": 
        short_df["Type2_Recode"][row] = 8
    elif short_df["Type2"][row] == "Fairy": 
        short_df["Type2_Recode"][row] = 9
    elif short_df["Type2"][row] == "Fighting": 
        short_df["Type2_Recode"][row] = 10
    elif short_df["Type2"][row] == "Psychic": 
        short_df["Type2_Recode"][row] = 11
    elif short_df["Type2"][row] == "Rock": 
        short_df["Type2_Recode"][row] = 12
    elif short_df["Type2"][row] == "Ghost": 
        short_df["Type2_Recode"][row] = 13
    elif short_df["Type2"][row] == "Ice": 
        short_df["Type2_Recode"][row] = 14
    elif short_df["Type2"][row] == "Dragon": 
        short_df["Type2_Recode"][row] = 15
    elif short_df["Type2"][row] == "Dark": 
        short_df["Type2_Recode"][row] = 16
    elif short_df["Type2"][row] == "Steel": 
        short_df["Type2_Recode"][row] = 17
    elif short_df["Type2"][row] == "Flying": 
        short_df["Type2_Recode"][row] = 18
        
short_df

C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Kieran\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

,#,Name,Type1,Type2,Generation,Type1_Recode,Type2_Recode
0,1,Bulbasaur,Grass,Poison,1,1,6
1,2,Ivysaur,Grass,Poison,1,1,6
2,3,Venusaur,Grass,Poison,1,1,6
3,3,VenusaurMega Venusaur,Grass,Poison,1,1,6
4,4,Charmander,Fire,NaN,1,2,
...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,6,12,9
796,719,DiancieMega Diancie,Rock,Fairy,6,12,9
797,720,HoopaHoopa Confined,Psychic,Ghost,6,11,13
798,720,HoopaHoopa Unbound,Psychic,Dark,6,11,16
799,721,Volcanion,Fire,Water,6,2,3

In [12]:
short_df.to_csv(r'./Resources/poke_recode.csv', index = False, header=True)

In [13]:
poke_df

,#,Name,Type1,Type2,Total,HP,Attack,Defense,SpAtk,SpDef,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [14]:
from sklearn.preprocessing import LabelEncoder
# making a specific dataframe to predict legendary or not
poke_df.dropna()
stats_df = poke_df[["Total","HP","Attack","Defense","SpAtk","SpDef", "Speed"]]
poke_df= poke_df.Legendary.astype(int)


# split them into an x and y
X=stats_df
y=poke_df

In [15]:
from sklearn.model_selection import train_test_split

In [17]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2)

In [18]:
# get linear regression
from sklearn.linear_model import LinearRegression

In [19]:
clf = LinearRegression()

In [20]:
# fit the data 
clf.fit(X_train,y_train)

LinearRegression()

In [21]:
# predict the model
clf.predict(X_test)

array([-0.02320837,  0.05163823,  0.20403252,  0.23932923,  0.13740627,
       -0.17644783, -0.10774194, -0.03734892,  0.03852028, -0.07251547,
        0.26305873,  0.39289165,  0.0741263 ,  0.17226639,  0.26724911,
        0.18389662, -0.03135218,  0.10763052,  0.17551979, -0.00103189,
       -0.04691042, -0.0427426 , -0.11623572, -0.09261363, -0.0063731 ,
       -0.08381058,  0.1367344 , -0.08201654, -0.03900061,  0.14011543,
        0.16708413, -0.1460907 , -0.00182771,  0.1184845 ,  0.12685758,
       -0.00487954,  0.1701166 ,  0.04729959,  0.10657578,  0.04299815,
       -0.17360708,  0.11037499, -0.10425465,  0.1006122 ,  0.1090084 ,
       -0.03201768,  0.13456876,  0.0729499 ,  0.0709406 , -0.0241006 ,
        0.08144171,  0.21011552,  0.08328441,  0.0739521 , -0.07004578,
       -0.04343327, -0.01936717,  0.09350991,  0.22718968, -0.03634991,
        0.00571714,  0.13145555,  0.18480972,  0.03659383, -0.08432386,
        0.12826999, -0.04512603,  0.00489506,  0.03656782,  0.37331991,
       -0.0272298 , -0.12839472,  0.21858519, -0.08459519, -0.04641215,
        0.22839007,  0.14583016,  0.02960279, -0.08677066,  0.04879077,
        0.20135131,  0.01476381,  0.01050308,  0.12646754,  0.00075393,
        0.11296084, -0.06293407,  0.17596943,  0.02437518,  0.11812733,
       -0.01392324, -0.07231832,  0.26425336,  0.14861285, -0.15887165,
       -0.01115818,  0.09964339, -0.01779596,  0.04982266,  0.13678938,
        0.16829938, -0.06929968,  0.28302873,  0.18504303,  0.23005852,
        0.1454223 , -0.11919114,  0.28737333, -0.1131219 , -0.02832039,
        0.26724911,  0.06765019,  0.13615325, -0.05423562,  0.35043594,
        0.11329601, -0.05968774,  0.35652171,  0.13211037,  0.05697923,
       -0.08364616,  0.07863736,  0.08139654,  0.09353959, -0.02921406,
        0.10408561,  0.09711273, -0.09411133, -0.00319164,  0.11443003,
        0.06252547,  0.4063686 , -0.08036974,  0.12295974,  0.28311456,
       -0.16821268, -0.00247755, -0.05756627,  0.07533426, -0.07847608,
       -0.07714987,  0.11100826,  0.28928875,  0.12224808, -0.05341952,
        0.26724911, -0.16974789,  0.23632785,  0.18662493,  0.03503707,
       -0.12938261,  0.13468191,  0.15705444,  0.09877187, -0.14624601,
       -0.04773758,  0.10582145, -0.11783541, -0.09173806, -0.19781999])

In [22]:
# check the score of the model

clf.score(X_test, y_test)

0.16992238211509947